version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB__DATABASENAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
